### ISSUE TITLE
[Feature request] Re-arrangement of repair docks and construction yard layout.

### ISSUE THREAD

**Issue by Crazyteitoku** [dragonjet/KC3Kai#129]
Hi, this is a very minor feature request from me but I think re-structuring the layout for repair docks and construction yard might be seen as a little more useful compared to what it is now. To demonstrate visually, please refer to the following screenshots.

The idea is loosely based on how Kancolle organises their layout which is basically from top to bottom as opposed from going left to right and downwards. 

http://imgur.com/fMns1Zb,eQzkICH#0

N.B.:
* There are two images in that link, please refer to the above in that link for images of before and after images.
* I had issues uploading images onto the github, not exactly sure what is going on and so the images had to be uploaded onto imgur instead.

**Comment by dragonjet** [comment]
ohh i see what you mean, this is a good idea, though we'll need to redo the mechanism.

The current is very easy to implement that you just need to change the HTML element's class to switch from 2 - 3 - 4 slots. If we'll do this, it will involve more javascript and probably more tinkering around with CSS.

We'll see in the future what we can do.

**Comment by bamboo3250** [comment]
Why don't we just use only one style for any number of slots? That would increase the consistency of the UI and make it easier for us to implement.

**Comment by dragonjet** [comment]
the first problem is with space xD there's so little vertical space to do 3+4+4 rows. and not enough horizontal space to do 4 icons.

I'm confident that a new theme for vertical layout would not have this problem though. Something that is 800px wide and is good for a top-bottom screen-panel orientation

I'd welcome new theme though, even some wikians are willing to design when they get the time. Fortunately, the current layout files are isolated and we can switch anytime under `src\pages\panel\themes`

**Comment by bamboo3250** [comment]
I think the new design that @Crazyteitoku proposed is quite good. That one uses "box-timers-4" class for 4 slots of repairs and constructions. How about we use that for 2 and 3 slots as well for top-bottom screen-panel orientation? We can design to make it look like the picture above. That should have enough space and look clean and neat to me.

btw, is the horizontal theme for the vertical panel? It looks that way to me though XD.

**Comment by Crazyteitoku** [comment]
Hate to sound stupid but @bamboo3250 [initially](https://github.com/dragonjet/KC3Kai/issues/129#issuecomment-112653077) I wasn't sure where you were for or against my proposed idea. Though as I can see latter on you are for my idea. I am not really fussy overall but just thinking how the layout if changed to properly (and accurately) reflect with the ships in dock so that one does not get confused for instance when they have all the docks/yards unlocked. This idea might also even work with those Free to Play (F2P) players as well as I can personally imagine the layout is more organised. Again an idea is an idea afterall.

Personally I have much to learn about the coding and hence how it all works. I may look into it after I am done with the [wiki](https://github.com/dragonjet/KC3Kai/wiki) work.

**Comment by dragonjet** [comment]
Ah what I meant by the layout is something like this

![Layouts](http://puu.sh/is0x9.png)

The panel usually tends to be the "opposite" of the layout name.
- On Vertical layout, panel tends to be wider, but shorter.
- On Horizontal Layout, it tends to be narrower, but taller.

Right now what we have is a tall panel for the horizontal layout.

I'm looking forward to a vertical layout that will be a top-down approach to game screen.

It will look something to this effect

![Planned vertical layout](http://puu.sh/is0Kc.png)

**Comment by bamboo3250** [comment]
hm I see. This is interesting. Is there any way to auto-detect the orientation of the panel whenever users change it? I would like to do a prototype for the vertical layout in the meantime the quest module is still under construction. I'll try my best to make it work with minimal changes to the code in backend.

@Crazyteitoku I saw your work with the wiki page. That 'Setup development build' section saved me a lot of time. I'm looking forward to seeing it completed. I'm also a KC3Kai user so I'm for any idea that makes it better. I'll work on this idea and the vertical version in this week and hopefully can finish it by next week. Anyway, nice to work with you though :+1:

**Comment by dragonjet** [comment]
My idea with switching layouts if via auto-detection
```
if($(window).width() >= 800){
	// vertical
}else{
	// horizontal
}
```
probably $.`addClass` / $.`removeClass` then it will change by itself

The problem with it is that I'm sure there are HTML differences between vertical and horizontal. But that would be the best scenario if we can just use CSS classes.

That's also a reason why I added `.theme-horizontal` in all CSS definitions in `src\pages\panel\themes\horizontal.css`, so that if we will have the ability to have vertical layout without refreshing, they would not conflict.

**Comment by Crazyteitoku** [comment]
@bamboo3250 O.o didn't know it helped. At this point in time I consider that the development build page is more or less done - at least to best extent that I could offer for windows developers/users. I don't use tortoisegit so I can't really fill out information on how to do it in detail. Glad that it could be of some help/use.

I noticed you have an avatar based on the same character that I chose for mine xD oh well nice to meet and work with you. Totally looking forward to seeing more and more contributors (better yet developers) to work on kc3 kai :+1:

**Comment by bamboo3250** [comment]
I am personally using SourceTree. I guess any software that supports git (even just git itself) also can work. As long as the contributor knows how to use git, he will know what to do. So I think there is no need to specify tortoisegit. Just my opinion though.

**Comment by dragonjet** [comment]
tbh @Crazyteitoku's guide reminded me of one important thing I totally forgot. One of my local friends asked how to get the latest version and I shot him down saying you'll need git. But then he can just download the zip from home page :stuck_out_tongue_closed_eyes:

**Comment by bamboo3250** [comment]
lol that's true. The URL is still the same even if there is a new update. 
btw, does the KC3Kai update automatically or we have to download new .crx file from the Chrome Web Store?

**Comment by dragonjet** [comment]
it auto-updates for people when I re-publish it on Webstore. By default Chrome check for updates on each extension every 5 hours and will download in the background if there is.

By the way @bamboo3250 before you try the vertical layout, let me first attempt to rewrite the library script for "Dashboard". I'm planning to make it an instantiatable class where we can just `new Panel()` for every theme we have. If it works well, we do not need to have JS changes for every theme and just pure HTML/CSS every new one we make.

**Comment by bamboo3250** [comment]
Okay, that sounds nice to have. Meanwhile I will fix other petty bugs I just found out.

**Comment by Crazyteitoku** [comment]
Haha just noticed these as well. Oh well the wiki now sees some use :stuck_out_tongue: 

@bamboo3250 never tried other git tools. I myself just use git cli but yeah not sure how to write for others and stuff, especially for tools that works around windows platform.

**Comment by dragonjet** [comment]
Update: the panel development took the opposite turn. Each theme should have its own definition: its own folder, own html/css/js file. Like a totally separate page with no connection to other themes.

I had to choose. Between extensibility vs flexibility. If we had every theme root from a single Panel class definition, it will be hard to implement theme-specific features. It would just result to each theme having different color scheme, which we can easily implement by background colors - which is not the point.

The point of themes is to have its own UI, clickable elements, different usability approaches, which could mean totally different frontend scripting. Thus we cannot use my plan to have it a single class you can just `new Panel()`. Though I'd have to say I'm still proud of the latest `src\library\modules\Panel.js`, which could've worked very well if only the old concept wasn't flawed.

New themes can still copy-paste the default (`src\pages\devtools\themes\default\`) but will need to maintain its own script.

Still, I'm not yet done and I don't know where this will take me XD

**Comment by bamboo3250** [comment]
I agree to have different files and folders for horizontal and vertical themes but it would be nice if we can change the color (e.g. from white theme to black theme) without adding any HTML or script files.

And yeah, just take time to enjoy the journey. This could be a milestone for KC3Kai so there is no need to rush.

**Comment by Crazyteitoku** [comment]
No rush, it seems more hassle than for what it is worth.

**Comment by tmerta** [comment]
Maintainability within a product is key, and by splitting out the orientations/themes into two completely separate trees means double the work. If such is really desired, I'd recommend moving towards an MVC/MVVM framework such as Angular. Define your logic in controllers/directives, and then the any view can bind to the controllers and share the same logic. All the code that currently exists in different modules, so to speak, could be moved to services to share and update information. I had started to do a POC of the panel in Angular, but wasn't going to dedicate much time unless interest was shown.

**Comment by dragonjet** [comment]
It also crossed my mind at some point, but I'm worried about performance in using Angular. Knowing Chrome's RAM usage, reports of lag, and countdown timer slowdowns, I didn't pursue the thought.

In the end, what I did was to really separate each theme into its own directory. Each one having its own html/css/js as seen on `src\pages\devtools\themes\default\`. It comes with its own benefits though.

There are still some library classes that each theme can utilize:
* `\src\library\modules\Panel.js`
* `\src\library\modules\Dashboard.js`

**Panel** is the page on the devtools panel itself. It manages multiple dashboards, because ideally, the panel will automatically switch vertical-horizontal vice versa depending on the window width. So it basically manages two instances of `Dashboard`.

**Dashboard** is a single container for an interface. A horizontal dashboard is a separate object than a vertical dashboard, but they're on the same page. Just different container.


One of my goals in rewriting the panel is to give each theme the flexibility in doing what it wants, without being restricted to a global set of actions. e.g. I don't want all themes to be forced into `$.clone().appendTo()` for each ship in the fleet, I don't want to restrict all themes to `$(".craftBox").show()` whenever you craft something. Each theme may have its own way of doing / reacting to these things. A theme may have it in a modal, the other maybe a fixed box on the side.

That's the reason `Panel.js` only help on basic actions such as switching between vertical/horizontal, etc.

Meanwhile, `Dashboard.js` paves the way to these custom actions. An instance of `KC3Dashboard` can take in "*listeners*". It can subscribe to a certain event that the `Network` script will trigger. For example, a `FleetChanged` event. Once the specific theme's listener is triggered, it can do it's own way of dealing with fleet changing, it can either animate or whatever it wants.

@tmerta Fortunately due to the new nature of how our devtools panels work - since each one has its own folder, html/css/js, it is still possible to use Angular on specific themes. The difference is the these theme would just not utilize `Panel.js` and `Dashboard.js` but can still subscribe to the `Network` Listener. This means you can still make an Angular-based theme if you want.

**Comment by dragonjet** [comment]
Related: Added new entries interface overhauls #155 #156 #157 #158 

This one will still be opened since the original suggestion is about the layout of timer icons, not the interfaces in general.

**Comment by bamboo3250** [comment]
So excited to see the new interface. Just tell us when u finish overhauls :smile:

**Comment by dragonjet** [comment]
![ss 2015-07-02 at 04 17 49](https://cloud.githubusercontent.com/assets/557312/8472681/e8201398-20d5-11e5-8222-7ee73c2be84c.jpg)
