### ISSUE TITLE
[Strategy Room] Sortie History and all gauges

### ISSUE THREAD

**Issue by bamboo3250** [dragonjet/KC3Kai#147]
At the moment we haven't had the battle history for EO 4-5.

**Comment by Crazyteitoku** [comment]
This was also indicated by Nanamin on kancolle.wikia.

**Comment by dragonjet** [comment]
moved to v10 release since strat room not available on beta

**Comment by dragonjet** [comment]
those delays :v

**Comment by bamboo3250** [comment]
Have you started working on this? Or have any brief idea about this feature?

**Comment by dragonjet** [comment]
The gauges should now be on the Strategy Room since last webstore release, it's supposed to be correct too and updates when the player visits the sortie page in-game. It also dynamically includes all maps, and not hard-coded like before. The only thing missing now is the sortie list - which I'm working on atm

**Comment by bamboo3250** [comment]
:+1:

**Comment by LostLogia4** [comment]
Kinda concerned with 12.2's milestone since tomorrow's the deadline for the next webstore release though...

**Comment by dragonjet** [comment]
topkek I removed milestones from the 12.2 issues. From now on I will not mark issues via "*want it to be done here*", but will now mark it via "*ah this one is next, it can be done here*"
