### ISSUE TITLE
NaN value in Strategy Room

### ISSUE THREAD

**Issue by bamboo3250** [dragonjet/KC3Kai#199]
I don't have this issue but someone has this. I still post it here to keep track

https://www.facebook.com/photo.php?fbid=723434847766353&set=p.723434847766353&type=1&theater

![11742820_723434847766353_742524332660617574_n](https://cloud.githubusercontent.com/assets/8078323/8622223/42a3f5ce-2765-11e5-8e2b-02fae36c4da7.jpg)

**Comment by Crazyteitoku** [comment]
Would be nice if the person is able to report which versions he/she is on. :stuck_out_tongue: 

To me (as a non-developer) it is either one of two things:
* The database has not obtained a complete listing of the ships data from since the game is to download that 1MB or so file at the beginning of the game (ship loading screen).
* The database is probably corrupted internally.

Have you also suggested the person in question to try and open up debug window whilst they are in strategy room? any errors might be more useful than just a screenshot in my opinion.

**Comment by dragonjet** [comment]
as I see it, he used the panel too late in the game, and not on startup

equipment list is only loaded at the start of the game or after sorties. if he opened it late, we don't have a list of his equipment and its IDs, which explains missing equipment icons on the right, and that the AntiSub / Evasion / LoS values are actually derived values where we deduct ship stats minus the equip stats. It will become NaN if there are not equip stats.

See sendai K2 probably has no equipment at all so there is no bad subtraction
