### ISSUE TITLE
[CRX] Version 10.8

### ISSUE THREAD

**Issue by Ekigome** [dragonjet/KC3Kai#201]
I'd like to try the newest version on Chromium, could we have the .crx? Thank you in advance.

**Comment by Crazyteitoku** [comment]
The latest version is in Google webstore, there is no need to grab the .crx file in order to install it (for chrome/chromium).

**Comment by dragonjet** [comment]
Does Chromium also support WebStore? tbh I don't know, but in case you're not able to, you can try the following guide:

https://github.com/dragonjet/KC3Kai/wiki/Setup-development-build#option-zip-download

**Comment by Crazyteitoku** [comment]
@dragonjet yeah Chromium does support webstore, that was how I got kc3 kai (back when it was circa v009 or earlier release) working before I got around to github builds.

**Comment by dragonjet** [comment]
@Crazyteitoku but as I remember it, Chromium does not support all our codes and ends up either white screen or being stuck in "Waiting for game actions" screen. There was this player who I even used TeamViewer on, coz KC3改 just won't work, only to discover she was using Chromium

**Comment by Crazyteitoku** [comment]
@dragonjet  True, in fact I just hit a snag: https://github.com/dragonjet/KC3Kai/issues/210 , will document more and update more as needed.

**Comment by Crazyteitoku** [comment]
The funny irony is that I suggested to Erupi (on kancolle wikia) to try Chromium because of some issue with flash or something and Erupi told me the version (of Chromium) made available for windows was much higher than the ones made for other platforms namely linux. On my end, the version reported is version 43.xxxxx (whatever minor versions google threw on :stuck_out_tongue_closed_eyes:) Whereas on Erupi it is version 45.xxxxx Also that the UI layout is different between these two platforms.

I think what may need to happen is really that those who are running Chromium on windows may need to really enable debugging options like the developers in order to try and get this to work. This however does not really need .crx file as it is possible to install the extension from webstore without any issues as far as I can see on my end. Should there be issues it would be nice if they can provide a more terse/verbose information from webstore as needed.

As for the .crx file, if really needed one can still use the likes of "Get me CRX" chrome extension - this extension works on my end and should theoretically work on windows as well.

**Comment by dragonjet** [comment]
ah thanks as always @Crazyteitoku  :+1:

In moving forward I will remove the advice to request for CRX version and instead download the a zip file from releases, which is not CRX mode but an archive of the source folder as we're doing in the betas.

**Comment by Crazyteitoku** [comment]
A zip of the github directory is satisfactory definitely. I mean crx is easily obtainable from webstore builds and I just don't think it is a necessity to always sign and compile each builds of github revisions into respective crx.

The only other likely case where (if anything) crx is needed is for cross-browser compatibility.
