### ISSUE TITLE
git + tortoisegit windows OS

### ISSUE THREAD

**Issue by rimedigit** [dragonjet/KC3Kai#220]
THIS IS NOT AN ISSUE OF KC3 PER SE BUT AN ISSUE IN THE INSTALLATION OF KC3 VIA GIT/TORTOISEGIT.
Hi, according to the installing instructions (github.com/dragonjet/KC3Kai/wiki/Setup-development-build), tortoisegit sounds easier to use than git, and i wanted to try it out, so i did. 
However, after havin installed it, when i right-clicked in my folder and clicked on "git clone...", an error window opened, saying that "Git for Windows (https://msysgit.github.io/) not found." This is exactly what it's written, word per word.
So it makes me install git, as in, it's mandatory and not optional. 
In fact, after having installed git in my computer, the error window does not even appear, and i can close the URL just fine.
So, yeah, I was said it would have been useful to report it.

Err, another thing. I was wondering if, I can download the latest assets with tortoisegit alone. But I forgot if you can do that with "git sync" or with the "pull" function, sorry.
So yeah, thank you for hearing me out.

**Comment by Crazyteitoku** [comment]
Part of the documentation is missing, would be nice if some developer/maintainer can kindly inform on how to go about on this so that relevant changes can be made on the wiki.

**Comment by dragonjet** [comment]
ah I revised CT's original article on setting up dev build, but I wasn't able to write additional info, I just moved stuff around xD

@Crazyteitoku yes we should outline 4 alternatives to getting dev build, but the since they all converge on loading unpacked extension its separated into a second section. Only the acquisition of files is needed on the first section

Yes you'll need both git and tortoise to make it work, but do note that it's usually buggy and we usually inform CT and erupi on chat in case it's not advised to pull yet
