### ISSUE TITLE
Taihou not Taiho

### ISSUE THREAD

**Issue by SanaNoHana** [dragonjet/KC3Kai#239]
Wrong Romaji. Fix please! :dart:

**Comment by McDohl** [comment]
forget to tell fusou also listed as fuso xD

**Comment by dragonjet** [comment]
what about yamashirou and nagatou?

**Comment by dragonjet** [comment]
jk. fixed in the commit above

**Comment by bamboo3250** [comment]
Fusou and Taihou have long vowels while Nagato and Yamashiro don't have. So those two are correct :3
Just a side note: 隼鷹 is translated as "Junyou". It's not wrong but may be misleading since it can be read as "Ju nyo u" (3 sounds) or "Ju n yo u" (4 sounds). So usually they put a ' in the middle to differentiate 2 cases. "Jun'you"  like in wiki page http://kancolle.wikia.com/wiki/Junyou looks better. This is trivial so if no one complains, we can leave it be like that.

**Comment by nicky008** [comment]
It's a bit pity in that wiki since the Kai Ni name is not put the stress symbol to separate like the others two. lolz

And in the wikia is no use long vowels mark symbol to emphasis (ex. Fusou -> Fusoū) for now yet. So we should use the reference from it for reducing the confuse.
