### ISSUE TITLE
Blur HQ name feature

### ISSUE THREAD

**Issue by dragonjet** [dragonjet/KC3Kai#254]
ability to click on HQ name, and it will become blurred for those who are cautious in doing screenshots. double tap will possibly also show up an overlay to cover the HQ name on top-left

**Comment by LostLogia4** [comment]
The mosaic overlay starts at around 112-114 from the left at X-coordinate.
Just fyi.

**Comment by dragonjet** [comment]
ah thanks, still haven't decided which approach to use but its a good thing to have on hand

**Comment by LostLogia4** [comment]
I thought it is toggled by clicking on the HQ name in the Admiral Panel?

**Comment by Crazyteitoku** [comment]
Instead of blurring, what about an option to just simply hide the HQ name? Something like what is already implemented for dismissing crafted items in the crafting box which is visible in bottom right of the vertical layout.

**Comment by dragonjet** [comment]
yes, I mean on what scripting/library to use xD

**Comment by nicky008** [comment]
@dragonjet Blurred like in any 18+ doujins? :love_hotel:

**Comment by dragonjet** [comment]
probably XD, or probably in some ecchi animes there are rays of light

**Comment by Crazyteitoku** [comment]
Nice! I mean I also want the ability to blur it if the HQ name could not be made invisible because that just gives me a bit of extra work to do by manually either blurring it out by hand or cropping it using some image editing tools. I just don't know how to translate a pseudo idea into the real thing. Anyhow :+1:
