### ISSUE TITLE
Battle Prediction

### ISSUE THREAD

**Issue by dragonjet** [dragonjet/KC3Kai#29]
Show results, damaged and ending HPs right when battle starts.

This will be applied to the mini-HP bar on the panel

**Comment by AlanSchaeffer** [comment]
I was about to open an issue which might be related to this, but I wanted to be able to see HP after battle ends but before I decide wether I want to continue sortie or end, would this count as a duplicate?

**Comment by dragonjet** [comment]
ah though it's possible but we should not trust it, and still rely on the after screen. the HP bar update when you're proceeding to the next node.

the way we can do this is by emulating the battle, checking who shot who and how much damage and calculating ourselves, but this might be different from how the server does calculations so it's really called "prediction".

**Comment by AlanSchaeffer** [comment]
Hmm... no fleet state data received on the victory/ranking screen?

**Comment by dragonjet** [comment]
Please do not mix this with the current HP bars that KC3改 have, which updates after battles. **We can trust and rely on that to proceed or not to proceed to next node**.

The KC3改 panel **HP bars always update after the battle with the CORRECT ending HPs**, and that will not change.

---

What this specific feature ("**Battle Prediction**") involves, is a **before-battle** prediction of what will happen, right when you **pick a formation**, even **before** the battle **animations** start - **which isn't normal**. You can see some of your ships got red in the panel even before they got hit in-game.

After the battle results screen, right **before** you **spin** the **compass** to the **next node**, all **HP bars** will **update** with the **correct values**

---

My reason to saying we should "not trust" prediction HP bars is that **players might not re-check** or ignore the updated and **real ending HPs after the battle results screen**, **which is wrong**.

**Comment by AlanSchaeffer** [comment]
Yeah, I figured what I wanted was something else. If no data on HP is returned before, then there's nothing that can be done about it; since it's only updated after I select continue sortie, if I do catch someone at red that I did not notice, all I can do is close the game and "blame the connection", which still beats finding out someone was at red the hard way

**Comment by bamboo3250** [comment]
I think now we can do this issue but I would like to change the name to "Battle Spoiler" instead of "Battle Prediction" (It would really spoil the joy of watching battle) xD. 

I'm going to add a button to toggle this spoiler in the Battle Mode panel (not in Settings) and remember it for the next battle.

For our ship girl side, I'll show the before-battle HP in blue and the after-battle HP in the real color.
For abyssal side, I'll show a red cross over their icons to indicate who are eliminated in that battle. Then we can decide to go into Night Battle or not.

What do you think about that?

**Comment by dragonjet** [comment]
wait, my original idea was to have two HP bars, e.g. for a `10px height` HP bar, it will become two `5px height` bars, the top one remains as the current HP, the bottom one will be the new HP, and will follow the color of the new HP, so he will know if after-battle is already red or still in orange

**Comment by bamboo3250** [comment]
Nice timing, I am about to do it. Then I will try your idea first :wink:

**Comment by bamboo3250** [comment]
Prediction cannot be more accurate :smile: 

![screen shot 2015-08-01 at 5 19 04 pm](https://cloud.githubusercontent.com/assets/8078323/9021372/97209cc0-3871-11e5-9c25-cbdde92870d1.png)

**Comment by dragonjet** [comment]
ah btw, should only show if `ConfigManager.info_battle` is enabled

**Comment by bamboo3250** [comment]
yeah, I'll remember that.

Btw, salute to my Orel Cruising team to take a lot of pain when doing this feature :sob:

**Comment by Crazyteitoku** [comment]
@bamboo3250 all in the glory for experimentation! :stuck_out_tongue_closed_eyes:
