### ISSUE TITLE
Battle Mode not retrieving info correctly.

### ISSUE THREAD

**Issue by happyh0rse** [dragonjet/KC3Kai#295]
Battle mode was working earlier on. FYI.

http://i.imgur.com/PyUyxm6.jpg

**Comment by dragonjet** [comment]
ah yes this is because of a change in the game API this update, we'll need to adjust

**Comment by dragonjet** [comment]
to everyone involved in the topic, it seems we cannot preemptively show enemies before compass anymore. game API does not give `api_enemy` anymore. I'm looking at `api_event_id` though, might be something.

http://pastebin.com/9pJGQWn5

**Comment by nicky008** [comment]
So they might change it for the upcoming event, then how about when the event ends?... Will this api be vanished later on or just stay here now and no `api_enemy`?

**Comment by dragonjet** [comment]
I think this is a permanent change, I fear we won't be seeing this feature again

**Comment by nicky008** [comment]
> If this is a permanent change.

gg devs...

**Comment by dragonjet** [comment]
One thing I would like to note here is that this API change is **NOT** because the devs discovered KC3改 and intentionally attempted to remove us of this feature.

The main API call `api_start2`, the source of our master data also had some changes. They also removed variables that aren't being used.

For example, previously all ship objects contain `api_afterlv` and `api_aftershipid`, which tells us what is the ship ID of the current ship's next remodel. Now, they removed these two variables from "max remodels" since of course, max remodels do not have a next remodel.

They also removed `api_afterfuel` and `api_afterbull` from max remodels since those two determine how much resource is needed for remodelling. While max remodels do not need this, they also had been removed.

These four variables however, remained on those who DO have next remodels.

It seems they really are trying to make API calls lighter by making each response smaller.

**Comment by Javran** [comment]
I also notice that `api_enemy` are gone.
Just did a sortie 2-3, took `A -> B -> E -> G` and recorded some traffic [here](https://gist.github.com/Javran/1e1fbec5b2eaced90ee8).

Hope it helps for finding out other approaches for enemy composition prediction.

**Comment by nicky008** [comment]
@dragonjet I though after what you said above, I finally realized they have an intentionally to do this (for lighter workload).

And your point-out in the first paragraph is a must, so the users don't have new misunderstanding in this KC3改.

**Comment by dragonjet** [comment]
@Javran ah thanks for the infos, with that I'm definitely interested in `api_event_id`

@nicky008 yep, I posted the link to this thread from my fb page

**Comment by FacelessJacket** [comment]
That.. sucks. Was anything else affected? Like if we had AS+ , the number of planes both sides have or whether there's a kanmasu drop or not?
Thanks for informing us btw.

**Comment by dragonjet** [comment]
@FacelessJacket not that we know of right now. Only those changes are the ones I noticed so far

**Comment by bamboo3250** [comment]
It was quite a shock to me. I can't believe this happened right before the event. Perhaps we should start rewriting the code handling the compass soon.

**Comment by dragonjet** [comment]
We can let everything else stay as is. The enemy faces will still show up when the battle starts. The only difference is the timing of when these abyss faces appear.
