### ISSUE TITLE
Name ship

### ISSUE THREAD

**Issue by McDohl** [dragonjet/KC3Kai#312]
![namevertical](https://cloud.githubusercontent.com/assets/13024936/8761199/bac68266-2d6d-11e5-8267-860c0980f59b.JPG)
![namehorizontal](https://cloud.githubusercontent.com/assets/13024936/8761200/bfac23a8-2d6d-11e5-9169-2128b999a2ac.JPG)

pretty sure Prinz Eugen Kai will have this problem too

**Comment by dragonjet** [comment]
another is `Hatsushimo Kai Ni`

**Comment by bamboo3250** [comment]
Yamashiro Kai Ni as well. I'm aware of this but it would look weird if we hide a part of their name. For example, Kai Ni may become Kai because the Ni word is hidden.

**Comment by dragonjet** [comment]
Yea, this is a bit problematic since we can't just cut it like the quests. Even with horizontal, we do get problems like #195, etc. Also with larger fonts such as the one we use for Japanese, it will surely cause problems especially their long ship-type names, compared to our 3-char max ship type codes.

To re-think our UI options. Do you guys think we'll have to use responsive grid? What I don't like about existing grids is that it really hard to put things where you want them to. It is good if we're making a website, yes, we can support desktop, tablets, and mobile. But for a devtool panel with so many elements where we try out best to avoid scrollbars, and where each pixel is very important - responsive grids will just waste important space, and users will need to vertically scroll like a website - not very game-like.

Any feedback on how we can resolve UI problems?

**Comment by bamboo3250** [comment]
How about we add "..." at the end of the name when the name is too long? We can add a tooltip to show the full name when the user hovers the mouse on it.

**Comment by LostLogia4** [comment]
Thanks to the changeover from Kai2 to Kai Ni, we've gotten spillover in out hands...
First things first, for the vertical mode, the font size at the name can be reduced.
Failing that, we can made a text-slide animation to reveal the whole text (not much better than bamboo3250's suggestion actually)

**Comment by nicky008** [comment]
aka. spoiler mouse click or mouse over to view?

(Oh, but the mouse click is a bit pain *** for many players too...)

**Comment by bamboo3250** [comment]
In case we don't want to do any action to see the name, we can reserve 2 lines at least for the name. That means we have to put the ship type somewhere else (like 300px horizontal panel). However, this way can only solve this problem temporarily. Probably may not work in a long run.

**Comment by nicky008** [comment]
Yeah, seem not work well in the future when there are more long-name ships implemented.

**Comment by dragonjet** [comment]
hm how did KCV go about this, why does it seem other viewers don't have UI problems and they've got alot of space. tbh really space is our problem. or is it just that we have more content :laughing:

**Comment by LostLogia4** [comment]
Because you try to fit everything in one piece. If we have multiple tabs or something we might have some more space to breathe on.

**Comment by JD-Kurotoshigami** [comment]
hmm... why not only put the "actual name" of the ship in the name slot, then the others (kai, kai ni, etc) beside the Level?

**Comment by McDohl** [comment]
gonna close this, since natsuiro already a solution to this
