### ISSUE TITLE
Hard to see enemy fleet formation in battle mode

### ISSUE THREAD

**Issue by bcc32** [dragonjet/KC3Kai#381]
Black on dark red doesn't really give the best contrast.  Might it be better to use a brighter color?

![formation](https://cloud.githubusercontent.com/assets/1239097/8886434/f0d9c178-321e-11e5-8f44-201a164b5c8f.png)

**Comment by dragonjet** [comment]
oh topkek changed it to png and didn't see this xD

**Comment by ethrundr** [comment]
Let me copy mine here as well:
"Regarding the enemy formation: In the current Battle Mode is located on the node number at the top-left of the enemy formation infobox.

Since it has dark background color with the dark dots indicating the formation, and being overlaid by the node number, then it's really difficult to read. Thus, I'd like to suggest two options:
<ul><li>Remove the number completely, since the current node can be known already by looking the branching history above it.</li><li>Keep the number, and make another circle in the right to indicate the formation.</li></ul>

Also, the circle background (or the dot) need to have lighter color, so it'll standout more and easily give information about the formation."

**Comment by dragonjet** [comment]
ah I think I'll do your suggestion 2: Keep the number, and make another circle in the right to indicate the formation.
