### ISSUE TITLE
Formation image not accurate for fleets less than size 6

### ISSUE THREAD

**Issue by bcc32** [dragonjet/KC3Kai#411]
![formation](https://cloud.githubusercontent.com/assets/1239097/8899734/00e46ab2-33ed-11e5-9003-e7947609c107.png)

**Comment by bamboo3250** [comment]
@bcc32 could you provide more details about this issue? For example, how many ship does the opponent's fleet has? Which outcome is expected?

**Comment by dragonjet** [comment]
I was thinking it should've been 6 opponents since we hide the circles if the spot isn't occupied. but it could be a matter of loading images from photobucket

iirc I was fixing this before, but ran out of test options, no more PvP enemies less than 6 so I postponed the test, and totally forgot afterwards :v

**Comment by bcc32** [comment]
Enemy fleet size was 1.

**Comment by McDohl** [comment]
i think it's fixed on latest dev's build. tried it and it shows properly

**Comment by dragonjet** [comment]
i think so too, tbh I forgot what I did but I was sure I was editing code and testing, might have been fixed at that time already. will close, and just re-open if v13 webstore still has it
