### ISSUE TITLE
Battle Info glitch(?)

### ISSUE THREAD

**Issue by Erupi** [dragonjet/KC3Kai#459]
http://i.imgur.com/PYIlPVE.png
Seems like it seems out of place. I might be just me though. I tried reloading the extension but it still occurs.

**Comment by ethrundr** [comment]
adding for another display glitch, don't know whether this only in me or not

it's usually work well, but since I updated to v13.0 via manual unpacking, the enemy formation details only showing two first enemies, and the rest are white:
![screen shot 2015-08-03 at 10 20 39](https://cloud.githubusercontent.com/assets/13522800/9029173/83a22d72-39c9-11e5-8c16-0fd567fe0cd4.png)

**Comment by bamboo3250** [comment]
@Erupi you are right. There is a stupid mistake in vertical.css :scream: 
@ethrundr Did you go to any map before going to 2-3?

**Comment by ethrundr** [comment]
@bamboo3250 just tried to several maps, and all of them only show at most 2 images, the rest are always white.

**Comment by bamboo3250** [comment]
Did you try closing the panel and open it again? Then see if the problem still persists or not.
