### ISSUE TITLE
Ask Quest Page

### ISSUE THREAD

**Issue by McDohl** [dragonjet/KC3Kai#465]
Am I the only one encounter this?

![fbfe697865b713f773e939980a65b9d3](https://cloud.githubusercontent.com/assets/13024936/9031970/0e413544-39e4-11e5-85c9-4a29a0ca2392.gif)

it's like 90%+ chance for 1st page not translated

https://github.com/dragonjet/KC3Kai/issues/308

**Comment by nicky008** [comment]
And then open the next 2nd page, the translating layer is coming back, right?

**Comment by dragonjet** [comment]
everyone has this? why I don't :open_mouth: 

any other details how to trigger?

**Comment by McDohl** [comment]
@nicky008 yeah...
@dragonjet I don't know but, every time I trigger the quest page mostly like that.

**Comment by bcc32** [comment]
I usually get it when I click on Ooyodo very quickly after opening quest page.

**Comment by McDohl** [comment]
but, I haven't click anything yet :open_mouth:

**Comment by dragonjet** [comment]
show for a portion of a second, then clears itself.

probably an API or a furniture asset being loaded after `api_get_member/questlist`

but there's none that I know of that loads after questlist :open_mouth:

**Comment by McDohl** [comment]
maybe put a timer like 1-1.5 secs for translation appear?

**Comment by bamboo3250** [comment]
If that's possible then we also can solve this problem
https://www.facebook.com/photo.php?fbid=10155819036460525&set=o.120558182729&type=1&theater

**Comment by dragonjet** [comment]
someone from himeuta reports this. asking him what version he is using. might need to reopen if confirmed 13+

**Comment by McDohl** [comment]
after @bamboo3250 fix, for me it still encounter this but its like 1 out 20 tries.

 And gonna report another bug. If your quest is marked done by kadokawa/kancolle itself for these kind of quest like sortie that not has counter (1 time only) / composition quest will make the translation went off.

**Comment by bamboo3250** [comment]
About the main issue, I think it's caused by the asynchronous callback of `chrome.runtime.sendMessage`. The best solution I can think of is polling, using a while loop until the quest overlay is cleared then we will show the quest translation. @dragonjet do you have any better idea?

**Comment by dragonjet** [comment]
wait what. on `library\modules\Network.js`, the `clearOverlays` call runs on every received request. I think it shouldn't be. If the game was loading a ship CG, music, equipment photo or anything, and only completed after showing quest page, it will clear.

Additionally, we should put it so that `clearOverlays` will not run if the API received is not `questlist`. If the quest page is loaded, what happens is that a `clearOverlays` is ran, and then the data is processed and `showOverlays` is called. but there is no guarantee which executes first.

Maybe for the `clearOverlays` condition, we can just add, `&& api_function != "questlist"` or something

**Comment by dragonjet** [comment]
I discovered the problem.

I turned on my sounds just now.
There is an asset being loaded after questlist, that actually clears the overlays when it loads XD

Ooyodo's voice!

**Comment by bamboo3250** [comment]
lol, I also always turn off the voice unless it is event. :joy:
