### ISSUE TITLE
[Feature request] reset HP gauge when user acknowledges that the ship has been repaired.

### ISSUE THREAD

**Issue by Crazyteitoku** [dragonjet/KC3Kai#478]
**Steps to reproduce**:
1. Send a damaged ship into the bath.
2. Wait for timer to finish counting on the said repaired ship from bath.
3: Go back into the docks, KC3 Kai removes the said ship from the bath but does not always reset the HP gauge. This is more easily reproduced if the user is either in fleet, resupply, remodel, docks, construction yard and not in other screens where going back to the main screen would automatically reset the HP gauge of the repaired ship.

**Severity**: Minor

**Comment by dragonjet** [comment]
hm I've known this since the very start of KC3 non-kai, but I planned to leave it at that, and iirc kcv doesn't also do this xD

one reason is that we also cannot 100% trust the timer because of its "Timer allowance" which is based on user. If his allowance is customized to ping earlier, we could even see a ship we marked as "complete repair, mark normal", going back to "being repaired" state when you go back to home screen.

**Comment by Crazyteitoku** [comment]
Ah I see, lel I thought it was an old bug but it was sort of overlooked because the fix would have been trivial. :stuck_out_tongue_closed_eyes: Oh well this feature request can be dismissed then.

**Comment by dragonjet** [comment]
aye
