### ISSUE TITLE
Missing Consumables Icon On Compass

### ISSUE THREAD

**Issue by BWinkKeyShellDinkInc** [dragonjet/KC3Kai#63]
On consumable drop node, icon of the drop did not show up on compass. Instead, it is shown as a grey circle.
Picture:
http://i.imgur.com/wQAX4BD.png

This could only happen for devmat, requires further testing on other consumable drops.

**Comment by dragonjet** [comment]
ah thanks for the report, it's not just for devmat, I haven't added consumables into the node icon list. the problem is that each of them has a number and I haven't verified which is which yet. The resource nodes 1 to 4 is fuel/ammo/steel/baux respectively. We'll just need to figure out the number counterpart of the consumables now.

**Comment by BWinkKeyShellDinkInc** [comment]
Would it be possible to replace the colour of the grey circle to the colour of the consumables? It could serve as a temporary fix, at least until the numbers are verified. The colour should be enough to identify the consumable drop.
