### ISSUE TITLE
Event map HP does not update until you reenter a map.

### ISSUE THREAD

**Issue by NicolaosGreene** [dragonjet/KC3Kai#662]
When you look at the event map HP in the strategy room in does not take into account you last sortie against the boss and shows the HP of the boss before the sortie. I.e. if you had cleared E-4 once so it said 3000/3500 and then cleared again so it should say 2500/3500, however, instead it will say 3000/3500 until you sortie to the map again.

**Comment by LostLogia4** [comment]
iinm that one was directly retrieved from mapinfo api call, which is only called when you go to the sortie menu. Adding this feature would require taking battle results into account and may be inaccurate until you sortie to the map again, which means we can only predict the remaining boss HP after sortie.

**Comment by NicolaosGreene** [comment]
fair enough, but it might be a good idea to include it since it would probably paint a closer picture

**Comment by ReiFan49** [comment]
i'm doing it

**Comment by dragonjet** [comment]
wait does #662 work on combined fleet? I only saw usage of index-7 but I think on combined fleet index-7 is the flagship on escort fleet

**Comment by ethrundr** [comment]
@NicolaosGreene I don't know if it's just my miss or not...
But previously, I've just dealt my 6th kill to E7, and the HP before the kill was 702.
Once I get back to the base, setting for docks and expedition, then I heading to the Strategy Room since someone asked me for the Ship's composition.

There, I refresh the page once, then navigating the game out to the Home, opening the sortie map, return Home once again, refresh again.
The HP was updated to 447 on the Sortie history upon the second refresh. I have no idea about the first refresh, though, since I forgot to check before refreshing the second time.

Between the last sortie (the one that chipped the bar down from 702 to 477) and the refresh attempt, I have done no sortie to the event map. However, I do perform a sortie to 1-5 in the meantime.

**Comment by dragonjet** [comment]
The thing is, it only updates when you go to this screen

![dragonjet 2015-08-19 08-58-49 35](https://cloud.githubusercontent.com/assets/557312/9346525/8c78e9ca-4650-11e5-8bf2-f35381a0fd2e.jpg)

**Comment by ethrundr** [comment]
@dragonjet mind share me some of your fuel and ammo? :cry: 
need it to clear E7 :cry:

**Comment by dragonjet** [comment]
trade for buckets :v
