### ISSUE TITLE
Number of equipment, not box per instance

### ISSUE THREAD

**Issue by dragonjet** [dragonjet/KC3Kai#67]
Put the number of equipment for each item e.g. **Drum Canister x10** instead of having 10 boxes for drum canisters.

**Comment by Crazyteitoku** [comment]
I agree partly. Maybe you could put a tally on the left hand side of the box where it is below the equipment statistics as well as putting a tally count for any of the equips that has been improved. This could greatly help those who has to maintain a profile of their wiki page somewhere.

What I don't agree is that we still need equips and where they have been placed on the ships. If that feature got removed it would be a backward step rather than a forward step.

**Comment by dragonjet** [comment]
ah will only combine and count those that are not equipped

**Comment by dragonjet** [comment]
Latest equipment list shows total number owned, worn and extras
