### ISSUE TITLE
[Feature request] Add tooltips to the plane symbols in the battle panel

### ISSUE THREAD

**Issue by NicolaosGreene** [dragonjet/KC3Kai#701]
When I was doing PvP battles today I was looking at the planes indicator on the panel (I assume the green to mean all planes and the red to mean bombers, but I can't find any documentation to confirm that nor is there a tooltip) and it listed that I had 7 bombers and it indicated that I had lost none however, Taihou, who I was using at the time holds 8 in her smallest slot and was fully refilled beforehand. Therefore I suspect there may be some error in the calculation of how the planes sections is showing information. Furthermore, some tooltips to indicate what those plane symbols mean might no be a bad idea either. Also a SS is provided below. Version is bb3a3e5e3cbc36d7955374fcd1d81df69fd9328a.
![bomberoddness](https://cloud.githubusercontent.com/assets/3627763/9395578/dfa251b8-4754-11e5-9d13-004a7af8df18.png)

**Comment by bamboo3250** [comment]
I guess the blue plane is a special plane belonged to a squadron (Tomonaga or Murata)? If that's correct then everything is clear. 

The number next to the green plane symbol means the number of planes that have AA stats. In this case, the blue plane in Taihou is also included with green planes. So that number will be 30 + 24 + 24 + 8 = 86. After that 17 of those were shot down so I think here there are 16 green planes and 1 blue plane shot down in the first phase. Then we only have 7 blue planes left for the second (bombing) phase. And here there is no blue plane were shot down anymore so it just showed only 7 according to the picture. 

I think giving a tooltip for those symbols could be a good idea.

**Comment by dragonjet** [comment]
^ that's true, I've also been trying to explain this to @JD-Kurotoshigami

he's actually trying to come up with a formula or something for it so we can show it better

though I'm really bad at math so... kek :v

**Comment by NicolaosGreene** [comment]
Yes it was Murata and thank you for the explanation, I couldn't find one. So I think I should change the title then.

**Comment by NicolaosGreene** [comment]
I just did a pvp with Taihou equipped with a ryuusei instead of one of the named squads and it still read 86, so it either is counting all planes or something funny is going on.

**Comment by bamboo3250** [comment]
Is there any BBV or CAV in your fleet at that time?

**Comment by bamboo3250** [comment]
@NicolaosGreene yeah, that's my mistake. The first number is actually the total number of planes and the negative number next to it is still the number of planes shot down in the fighter phase.
