### ISSUE TITLE
Timers a bit unsynchronized

### ISSUE THREAD

**Issue by AlanSchaeffer** [dragonjet/KC3Kai#87]
This is one that is hard to explain or even reproduce, probably. It might have anything to do with the environment I'm running this on, or maybe something related to being a script on Chrome or even the game itself may have a different ratio of time, but what I do know is that the timers shown in game and the timers shown in the KC3 panel are unsynchronized. There were times when I left the game running and upon returning to the home area, the timers got refreshed with the server values and a whole 4 minutes were shaved off from my Kitakami's repair timer compared to what was showing there before.
If I leave the docks open and compare the timers, it is a small difference I cannot perceive at all (other than the normal different tick times of the timers due to starting at different moments), I haven't tried leaving it for long periods of time to see if it gets unsynchronized with time.

**Comment by Crazyteitoku** [comment]
I have noticed similar issues on my end as well. However the variances was not as bad as reported; the variances were on a much smaller manner in scale.

Is your computer set to sync with an online time server at pre-defined intervals? If so try turning it off for a few hours and whilst it is off test to see if during in that time when the ships are either sent to be repaired or constructed. From there on, compare the time it takes for the ships to be ready to leave the docks/yards versus the time indicated on KC3 Kai. In this particular case I have tested it with only docks portion and there was a variation of approximately 16 seconds between the timer stated on the dock versus the timer indicated on the viewer. This testing method I devised included considerations for the "< 1 minute dock repair" bug.

**Comment by ReiFan49** [comment]
having a sleep/hibernation might weakens the timer.
and iirc, setInterval / setTimeout for a long time might lead to inaccuracies, because these timers designed to delay thing for N ms (which is in this case is 1000 ms) and performs the action later on after 1000 ms, (which need to be re-calibrated after a single use to prevent offseting later on by 1 second or more)

**Comment by dragonjet** [comment]
ah I'm opening the possibility this might also be connected to the alleged "slowdown" when you're on a different tab.

we had no reports like this on old KC3, which might be because back then, the countdown is done be an invisible "background" page which always runs in the background, hence the name. This is supposedly not affected by other factors such as switching tabs, so I might try moving the whole countdown to the background page first and see if it fixes this

**Comment by dragonjet** [comment]
The v10 timers will now depend on completion time, and will not "countdown" (-1 per second). What it does is that every second, it calculates difference between the time now vs completion time and will always return accurate results regardless of browser slowdown.
